services:
  - type: web
    name: starcoder-api-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: API_KEYS
        value: dev-key-12345:developer:100,free-user-key:free_user:10
      - key: SECRET_KEY
        generateValue: true
      - key: MAX_MEMORY_MB
        value: 450
      - key: MAX_CONCURRENT_JOBS
        value: 3
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: starcoder-data
      mountPath: /app/data
      sizeGB: 1

